#!/bin/bash
opt_sol=${1:-"opt_sol.cpp"}
brute_force=${2:-"brute_force.cpp"}
generator=${3-"generator.cpp"}
if [[ $opt_sol != *.cpp ]]
then
    opt_sol="$opt_sol.cpp"
fi
if [[ $brute_force != *.cpp ]]
then
    brute_force="$brute_force.cpp"
fi
if [[ $generator != *.cpp ]]
then
    generator="$generator.cpp"
fi
echo "Testing $opt_sol against $brute_force with $generator"
for((i=1;;++i));do
    echo $i
    # Call generator and pipe to input
    ./$generator > input
    ./$opt_sol < input > out1
    ./$brute_force < input > out2
    diff -w out1 out2 || break
done