#!/bin/bash
set -e
opt_sol=${1:-"opt_sol"}
generator=${3-"generator"}
if [[ $opt_sol == *.cpp ]]
then
    opt_sol=${opt_sol%".cpp"}
fi
if [[ $generator == *.cpp ]]
then
    generator=${generator%".cpp"}
fi
if ! test -f ../${opt_sol}.cpp
then
    echo "${opt_sol}.cpp does not exist"
    exit 1
fi
if ! test -f ${generator}.cpp
then
    echo "${generator}.cpp does not exist"
    exit 1
fi
echo "Testing ${opt_sol}.cpp with ${generator}.cpp for TLE"
./${generator}.cpp compile
g++ -std=c++20 ../${opt_sol}.cpp -o ./${opt_sol} -Wall -O2 -Wextra -Wno-sign-conversion -Wshadow
for((i=1;;++i));do
    echo $i
    # Call generator and pipe to input
    ./$generator > input
    ./$opt_sol < input > out1
done